### ISSUE TITLE
Prevent quickcourselist block from being added when user isn't allowed to use it

### ISSUE THREAD

**Issue by abias** [marxjohnson/moodle-block_quickcourselist#3]
Hi,

sorry for double-posting, but I don't know if you are subscribed to Moodle Tracker.

Please have a look at http://tracker.moodle.org/browse/CONTRIB-3567

Thanks in advance
Alex

**Comment by marxjohnson** [comment]
The applicable_formats method isn't the best place to do this, we've now got the quickcourselist:addinstance and quickcourselist:myaddinstance capabilities which allow us to control which users can add the block.  I've tweaked the default permissions so that only those allowed to use the block should be able to add it to their pages, they can be given to additional users per site as required.

**Comment by abias** [comment]
Well, quickcourselist:addinstance and quickcourselist:myaddinstance is a better solution, of course. But these capabilities have not been there when I posted this ticket 2 years ago.

Thanks for having a look at this finally.

Alex
